### ISSUE TITLE
Expand the context concept

### ISSUE THREAD

**Issue by TelegramSam** [TelegramSam/DIDCommExamples#8]
There are two types of context - one for the contact (did), and one for threads, specified in the thid attribute of messages. 
Adjust the context mechanism to have both thread and contact mechanisms.
Change the context usage to use getter and setter methods.
Every time a context entry is set, record the timestamp it was set.
Add the necessary code to add a context storage engine that is not in memory, such as a postgresql database.
retain the ability to use an in memory storage engine for testing and demonstrations.
storage engines should abide a common interface, also included.

**Comment by uthentic-ai** [comment]
The work for this issue has been completed, and a pull request (#9) has been created. I will now run some verification checks to ensure everything is working as expected.

**Comment by uthentic-ai** [comment]
I am now running completion checks to verify that all requested tasks are fully completed.

**Comment by uthentic-ai** [comment]
I am now running build and code quality checks on the modified code for Issue #8.

**Comment by uthentic-ai** [comment]
I am now running completion checks to verify that all requested tasks are fully completed.

**Comment by uthentic-ai** [comment]
I am now running build and code quality checks on the modified code for Issue #8.
